Style `What's On` page
WordPress/wp20.wordpress.net pull request #40
Opened 2023-04-03 21:36 UTC by iandunn

See #3

2023-04-03 21:37 UTC, iandunn commented
This is still a WIP. So far it's just the mobile design.

2023-04-03 22:36 UTC, iandunn commented
Hey @marko-srb 👋🏻  I've started implementing the design and have a few questions:

* Should the titles of individual events have a different color or underline, to inform the user that they're links? You can [see examples of live content on the staging site](https://wp20.mystagingwebsite.com/whats-on/).
* I wonder if some users might be confused that the event search box is separated from the list that it filters? On mobile the map may take up the rest of the fold, so they won't see the list updating as they type, and nothing will happen if they hit enter. This screenshot doesn't have all the styles done yet, but I think it's close enough to show how it'd look if someone hasn't scrolled down yet:

    ![Screenshot 2023-04-03 at 3 33 43 PM](https://user-images.githubusercontent.com/484068/229641455-f4e7c73a-dd21-4d6e-bd81-dffed542600e.png)

    We could make the page automatically scroll down to the list when they hit enter, but my instinct is that it'd be a better UX to show the search box next to the elements that it affects. What do you think?

2023-04-04 11:53 UTC, marko-srb commented
@iandunn 

Thanks for the questions. Here are the answers:

> Should the titles of individual events have a different color or underline, to inform the user that they're links? You can [see examples of live content on the staging site](https://wp20.mystagingwebsite.com/whats-on/).

Sure. That sounds good, let's have them in blue.

> I wonder if some users might be confused that the event search box is separated from the list that it filters? On mobile the map may take up the rest of the fold, so they won't see the list updating as they type, and nothing will happen if they hit enter. This screenshot doesn't have all the styles done yet, but I think it's close enough to show how it'd look if someone hasn't scrolled down yet:

Yup, that's the issue here, but after multiple discussions Pablo wanted it above the map on both desktop and mobile. I guess users can get results in both map and the list below the map, so what we can do is just slightly scroll the user below so they see only the map and they can scroll for individual events. Does that work well in your opinion? As it is not scrolling them all the way to the listings, but just a bit to the map, with selected results. 

CC:
@jasmussen
@pablohoneyhoney

2023-04-04 20:16 UTC, iandunn commented
Sounds good 👍🏻 I opened #42 for that specifically, to help manage the scope on this issue.

2023-04-06 02:15 UTC, adamwoodnz commented
Perhaps we should have a 'No meetups match your search' message?

![wp20 mystagingwebsite com_(iPhone X)](https://user-images.githubusercontent.com/1017872/230255429-66da37a2-2c81-4663-9964-7ac1cab1ee8d.png)

2023-04-06 02:20 UTC, adamwoodnz requested changes
This is looking great!

Some minor suggestions on the styles. Only major is the theme mod to one column layout.

2023-04-06 02:20 UTC, adamwoodnz commented on wp-content/themes/twentyseventeen-wp20/style.css
> +	align-items: flex-end;
These styles aren't applying for me (local or sandbox) because the theme is set to `one-column`

![Screen Shot 2023-04-06 at 1 32 48 PM](https://user-images.githubusercontent.com/1017872/230250440-18d95b46-c6e8-4ab9-a930-d38baadea3db.jpg)

Have you got that [mod](https://github.com/WordPress/wp20.wordpress.net/blob/trunk/env/setup.sh#L7) applied?

2023-04-06 02:20 UTC, adamwoodnz commented on wp-content/plugins/wp20-meetup-events/views/events-list.php
Can't comment on the lines directly, but maybe we should run the event group (L14) and name (L19) through `prevent_widows_in_content`?

2023-04-06 02:20 UTC, adamwoodnz commented on wp-content/themes/twentyseventeen-wp20/style.css
>  	color: var(--wp20--color--grey-6);
There's a semantic color for this

```suggestion
	color: var(--wp20--color--text-meta);
```

2023-04-06 02:20 UTC, adamwoodnz commented on wp-content/themes/twentyseventeen-wp20/style.css
> +	gap: 30px;
I think 28px is close enough and matches other spacings across the site

```suggestion
	gap: var(--wp20--spacing--small);
```

2023-04-06 02:20 UTC, adamwoodnz commented on wp-content/themes/twentyseventeen-wp20/style.css
> +		row-gap: 22px;
I think 20px is close enough and matches other spacings across the site

```suggestion
		row-gap: var(--wp20--spacing--xsmall);
```

2023-04-06 02:20 UTC, adamwoodnz commented on wp-content/themes/twentyseventeen-wp20/style.css
> +}
The styles are written mobile first, so it would make sense to reverse this

```suggestion
#wp20-events-query-desktop {
	display: none;
}
```

Just need to be careful when doing the switch that the right input is displayed at 768px. I assume that's the mobile one, so the media query for showing desktop will be `min-width: 769px`, rather than `min-width: 48em`

2023-04-06 16:00 UTC, iandunn commented on wp-content/themes/twentyseventeen-wp20/style.css
> +	align-items: flex-end;
Doh, I didn't 🤦🏻‍♂️  Great catch, thanks!

Fixed in a98aa37

2023-04-06 16:05 UTC, iandunn commented on wp-content/plugins/wp20-meetup-events/views/events-list.php
👍🏻 fixed in 1cf4717

2023-04-06 16:07 UTC, iandunn commented on wp-content/themes/twentyseventeen-wp20/style.css
>  	color: var(--wp20--color--grey-6);
Thanks! Fixed in 2e1a7b7

2023-04-06 16:10 UTC, iandunn commented on wp-content/themes/twentyseventeen-wp20/style.css
> +	gap: 30px;
That sounds good to me 👍🏻

2023-04-06 16:38 UTC, iandunn commented on wp-content/themes/twentyseventeen-wp20/style.css
> +}
Ah, the ones I'd encountered seemed to be desktop-first, so I did it that way here for consistency. Looking through more comprehensively, though, it looks like it's a mix of mobile-first and desktop-first.

Do you think this should be changed to mobile-first? I don't have a strong opinion.

2023-04-06 20:09 UTC, iandunn commented
> Perhaps we should have a 'No meetups match your search' message?

That's a good idea. Added in [8b5e86b](https://github.com/WordPress/wp20.wordpress.net/pull/40/commits/8b5e86bf964dd61c6f2cf63a613aed9027bf591f) 👍🏻

2023-04-07 15:42 UTC, iandunn commented
I'm gonna go ahead and merge this so folks can [review it on the staging site](https://github.com/WordPress/wp20.wordpress.net/pull/48#issuecomment-1500213793), but feel free to open new issues if there's anything to iterate on.

2023-04-07 15:43 UTC, merged